config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'
  get 'sessions/new'
  #post '/signup',  to: 'users#create'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :podcasts
  resources :favorites
  post '/favorites', to: 'favorites#create', as: 'create_favorite'
  delete '/favorites/:id', to: 'favorites#delete', as: 'delete_favorite'
  post '/change_avatar/:id', to: 'users#change_avatar', as: 'change_avatar'
  resources :users do
    member do
        get :following, :followers
      end
    end
  resources :follows, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_create :set_default_avatar

  #validations
  before_save { self.email = email.downcase }
  validates :first_name,  presence: true, length: { maximum: 50 }
  validates :last_name,  presence: true, length: { maximum: 50 }
  validates :username,  presence: true, length: { maximum: 50 },
                  uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: VALID_EMAIL_REGEX },
                  uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  #attr_accessors
  attr_accessor :remember_token

  #relations
  has_many :favorites, dependent: :destroy
  has_many :podcasts, through: :favorites
  has_many :active_follows, class_name:  "Follow",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_follows, class_name:  "Follow",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_follows, source: :followed
  has_many :followers, through: :passive_follows, source: :follower

  #basic methods

  def full_name
    "#{self.first_name} "+"#{self.last_name}"
  end

  def set_default_avatar
    baccano_id = Digest::MD5::hexdigest(rand(1..100).to_s)
    self.img_url = "https://avatar.baccano.io/#{baccano_id}"
  end

  def avatar
    self.img_url
  end


  #login/auth

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    if remember_digest.nil?
      false
    else
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  #relationship methods

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def active_follows_ids
    self.active_follows.map { |a_f| a_f.followed_id }
  end

  #podcast methods

  def add_favorite(podcast)
    podcasts << podcast
  end

  def remove_favorite(podcast)
    podcasts.delete(podcast)
  end

  def podcasts?(podcast)
    podcasts.include?(podcast)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]

  def index
    @users = User.all

  end

  def show
    #@user = current_user
    @user = User.find(params[:id])

  end

  def new
    @user = User.new

  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      log_in @user
      flash.now[:message] = "Welcome to the Sample App!"
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:message] = "Your Profile has been updated"
      redirect_to user_path(current_user)

    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to login_path
  end

  #relations show

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_following'

  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_followers'
  end

  def change_avatar
    @user = User.find(params[:id])
    new_avatar = @user.set_default_avatar
    @user.avatar = new_avatar
    user_avatar = @user.avatar
    @user.update(avatar: user_avatar)
    render 'show'
  end

end

app/helpers/users_helper.rb
module UsersHelper


    def user_params(*args)
      params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :bio, :img_url)
    end

    def logged_in_user
      unless logged_in?
        flash.now[:message] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to :root unless current_user?(@user)
    end

end

app/views/users/edit.html.erb
<h2 class="users">Update Your Profile</h2>


  <%= form_for @user do |f| %>
  <h3 class="users"><%= f.label :first_name %>:</h3>
  <p class="users"><%= f.text_field :first_name %></p>

  <h3 class="users"<%= f.label :last_name %>:</h3>
  <p><%= f.text_field :last_name %><br />

  <h3 class="users"<%= f.label :username %>:</h3>
  <p><%= f.text_field :username %><br />

  <h3 class="users"<%= f.label :email %>:</h3>
  <p><%= f.email_field :email %><br>

  <h3 class="users"<%= f.label :bio %>:</h3>
  <p><%= f.text_area :bio %><br>

  <%#<p><%= fields_for :avatar do |user_avatar| %>
  <h3 class="users"><%= f.label :avatar %>:</h3>
  <p><%= button_to "Change Avatar", edit_user_path(@user), method: :post%>

  <%#<%end%>

  <% if @user.errors.any? %>
    <div>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <%end%>

  <p><%= f.submit "Update Profile" %>
<% end %>

app/views/users/follow.html.erb
<%= form_for current_user.active_follows do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow" %>
<% end %>

app/views/users/index.html.erb
<h2 class="users">Users</h2>
  <ul>
    <% @users.each do |user|%>
      <%if user.id != current_user.id %>
        <p> <%=image_tag "#{user.avatar}"%><br>
            <%=link_to user.username, user_path(user)%>

              <% if !current_user.active_follows_ids.include?(user.id) %>
                 <%= button_to "Follow", follows_path(:id => user.id), method: :post %>
               <%else%>
                 <%= form_for current_user.active_follows.find_by(followed_id: user.id),
                              html: { method: :delete } do |f| %>
                   <%= f.submit "Unfollow" %>
                 <% end %>
            <%end%>
      <%end%>
    <%end%>
  <ul>
<p><%= button_to "Return to My Profile", user_path(current_user), method: :get%></h3>

app/views/users/new.html.erb
<h2 class="users">New User<h1>
  <h3>

  <%= form_for @user do |f| %>
  <h3 class="users" ><%= f.label :first_name %>:</h3>
  <p><%= f.text_field :first_name %><br />

  <h3 class="users"><%= f.label :last_name %>:</h3>
  <p><%= f.text_field :last_name %><br />

  <h3 class="users"<%= f.label :username %>:</h3>
  <p><%= f.text_field :username %><br />

  <h3 class="users"<%= f.label :email %>:</h3>
  <p><%= f.email_field :email %><br />

  <h3 class="users"<%= f.label :password %>:</h3>
  <p><%= f.password_field :password %><br />

  <h4 class="users"> Tell us about yourself! </h3>
  <h3 class="users"<%= f.label :bio %>:</h3>
  <p><%= f.text_area :bio %> <br />

  <% if @user.errors.any? %>
    <div>
      <ul class="users">
      <% @user.errors.full_messages.each do |message| %>
        <li class="users"  ><%= message %></li>
      <% end %>
      </ul>
    </div>
  <%end%>

  <p><%= f.submit "Create Profile" %>
<% end %>

app/views/users/show.html.erb
<% if flash[:message] %>
  <p class="flash"><%= flash[:message] %></p>
<%end%>

<%# BASIC PROFILE DISPLAY %>
<% if @user.id == current_user.id  %>

  <h2 class="users"> My Profile </h2>
<% else %>
  <h2 class="users"><%="#{@user.username.upcase}"%></h2>

<%end%>

<body class="users">
    <p><%=image_tag "#{@user.avatar}"%><br>
    <%= @user.full_name %>
    <h3 class="users"> Bio:</h3> <%= @user.bio %>
    <h3 class="users">E-mail:</h3> <%=mail_to @user.email %>




    <p><a href="<%= following_user_path(@user) %>">
        <%= @user.following.count %>
      following
    </a> |
    <a href="<%= followers_user_path(@user) %>">
        <%= @user.followers.count %>
      followers
    </a>


<%# FOLLOWED PODCAST DISPLAY %>

    <ul class="users" >
      <h3 class="users" >Favorite Podcasts:</h3>
    <% if @user.podcasts.length == 0 %>
        <% if current_user.id == @user.id %>
          None yet! Get listening!
        <%end%>
    <%end%>
    <%@user.podcasts.each do |podcast|%>
    <p><%=link_to podcast.title, podcast_path(podcast.id)%>
    <%end%>
    </ul>


  <%# LINKS TO %>

    <% if @user.id == current_user.id  %>
      <p><%= link_to "Log out", logout_path, method: :delete %>
      <p><%= button_to "Update profile", edit_user_path(@user), method: :get %>
      <p><%= button_to "Delete profile", @user, method: :delete, data: { confirm: "Are you sure you want to delete your profile?"} %>
      <p><%= button_to "Change Avatar", change_avatar_path(@user), method: :post%>

     <% else %>
      <%# if current_user doesn't follow @user%>
      <% if current_user.followers.include?(@user)%>
           <%#see user.rb for method %>
        <p><%= button_to "Unfollow", follow_path(:id => @user.id), method: :delete %>
      <% else %>
      <%# if current_user follows @user%>
        <p><%= button_to "Follow", follows_path(:id => @user.id), method: :post %>
      <%end%>
      <p><%= button_to "Return to My Profile", user_path(current_user), method: :get%>
    <% end %>



</body>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
      <%= baccano_for @user, size: 30 %>
      <h3><%= @user.full_name %>'s <%= @title%></h3>
      <%#<p><%= link_to "view my profile", @user %>
      <%#<p><b>Favorite Podcasts:</b> <%= @user.podcasts.count %>

      <% if @users.any? %>
        <div>
          <ul>
          <h3><%=@users.count%> <%= @title%>:</h3>
          <% @users.each do |user| %>
            <li><%= link_to baccano_for(user, size: 20), user %>
                <%= user.full_name %>
                <% if @title == "Following" %>
                <%# unfollow button or follow back button depending on followers/following%>
                  <p><%= button_to "Unfollow", follow_path(:id => @user.id), method: :delete %>
                <% end %>
                <% if @title == "Followers" %>
                  <p><%= button_to "Follow Back!", follows_path(:id => @user.id), method: :post %>
                <% end %>
          <% end %>
            <ul>
          </div>

    <p><%= button_to "Return to My Profile", user_path(current_user), method: :get%>
      <% end %>

app/views/users/show_followers.html.erb
<% provide(:title, @title) %>
      <%=image_tag "#{@user.avatar}"%>
      <h3>My <%= @title%></h3>
      <%#<p><%= link_to "view my profile", @user %>
      <%#<p><b>Favorite Podcasts:</b> <%= @user.podcasts.count %>

      <% if @users.any? %>
        <div>
          <ul>

          <% @users.each do |user| %>

            <%=image_tag "#{user.avatar}"%>
                <h2><%= user.username %></h2>
                <p> <%= user.username%>'s Podcasts:
                  <% user.podcasts.each do |user_podcast|%>

                  <p> <%= link_to user_podcast.title, podcast_path(user_podcast.id)%>
                  <%end%>

                <% if !current_user.active_follows_ids.include?(user.id) %>
                  <p><%= button_to "Follow Back!", follows_path(:id => user.id), method: :post %>
                <%else%>
                  <%= form_for current_user.active_follows.find_by(followed_id: user.id),
                               html: { method: :delete } do |f| %>
                    <%= f.submit "Unfollow" %>
                  <% end %>
                <% end %>

          <% end %>
            <ul>
          </div>
      <% else %>
        No Followers Yet!
      <% end %>

    <p><%= button_to "Return to My Profile", user_path(current_user), method: :get%>

app/views/users/show_following.html.erb
<% provide(:title, @title) %>
      <%=image_tag "#{@user.avatar}"%>
      <h3>My <%= @title%></h3>
      <%#<p><%= link_to "view my profile", @user %>
      <%#<p><b>Favorite Podcasts:</b> <%= @user.podcasts.count %>

      <% if @users.any? %>
        <div>
          <ul>
          <h3><%=@users.count%> <%= @title%>:</h3>
          <% @users.each do |user| %>
            <%=image_tag "#{user.avatar}"%>

                <h2><ul><%= user.username%>'s Podcasts:</h2>
                  <% user.podcasts.each do |user_podcast|%>
                  <p> <%= link_to user_podcast.title, podcast_path(user_podcast.id)%>
                  <%end%>
                  </ul>
                <%= form_for current_user.active_follows.find_by(followed_id: user.id),
                             html: { method: :delete } do |f| %>
                  <%= f.submit "Unfollow" %>
                <% end %>
          <% end %>
            <ul>
          </div>
      <% else %>
        Not Following Anyone Currently!
      <% end %>

    <p><%= button_to "Return to My Profile", user_path(current_user), method: :get%>

app/views/users/unfollow.html.erb
<%= form_for current_user.active_follows.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow" %>
<% end %>